name: fluids
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - conda=4.13.0
  - conda-content-trust=0.2.0
  - conda-package-handling=1.8.1
  - console_shortcut=0.1.1
  - cryptography=42.0.5
  - idna=3.7
  - jupyter
  - jupyterlab=4.0.11
  - matplotlib=3.8.4
  - nodejs=18.18.2
  - notebook=7.0.8
  - numpy=1.26.4
  - openssl=3.0.14
  - pip=24.0
  - plotly=5.22.0
  - pycosat=0.6.6
  - pycparser=2.21
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.19
  - requests=2.32.2
  - ruamel_yaml=0.15.100
  - scipy=1.9
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - tqdm=4.66.4
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.43.0
  - xarray=2023.6.0
  - yaml=0.2.5
